import { rejectIrrelevantFacets } from '..';

describe('rejectIrrelevantFacets', () => {
  const count = 2;
  const locale = 'en';

  const facets = [
    {
      id: 'Variable',
      label: 'Variable',
      values: [
        {
          id: '0|Total emissions, Index 1990 = 100#INDEX_1990#',
          code: 'INDEX_1990',
          label: 'Total emissions, Index 1990 = 100',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Total man-made emissions#TOT#',
          code: 'TOT',
          label: 'Total man-made emissions',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Total emission intensities#INTENSITY#',
          code: 'INTENSITY',
          label: 'Total emission intensities',
          order: 0,
          count: null,
          isDisabled: true,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Total emission intensities#INTENSITY#|Total emissions per unit of GDP, Kg per 1000\n\t\t\t\t\t\tUSD#TOT_GDP#',
          code: 'TOT_GDP',
          label:
            'Total emissions per unit of GDP, Kg per 1000\n\t\t\t\t\t\tUSD',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Total emission intensities#INTENSITY#',
          level: 1,
          path: ['Total emission intensities#INTENSITY#'],
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Pollutant',
      label: 'Pollutant',
      values: [
        {
          id: '0|Nitrogen Oxides#NOX#',
          code: 'NOX',
          label: 'Nitrogen Oxides',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Carbon Monoxide#CO#',
          code: 'CO',
          label: 'Carbon Monoxide',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Sulphur Oxides#SOX#',
          code: 'SOX',
          label: 'Sulphur Oxides',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 1,
      hasPath: true,
    },
    {
      id: 'datasourceId',
      label: 'datasourceId',
      values: [
        {
          id: 'ds:qa:stable',
          code: '',
          label: 'ds:qa:stable',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: null,
          path: null,
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Country',
      label: 'Country',
      values: [
        {
          id: '0|Non-OECD Economies#NMEC#',
          code: 'NMEC',
          label: 'Non-OECD Economies',
          order: 0,
          count: null,
          isDisabled: true,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Australia#AUS#',
          code: 'AUS',
          label: 'Australia',
          order: 10,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Austria#AUT#',
          code: 'AUT',
          label: 'Austria',
          order: 20,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Costa Rica#CRI#',
          code: 'CRI',
          label: 'Costa Rica',
          order: 70,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Czech Republic#CZE#',
          code: 'CZE',
          label: 'Czech Republic',
          order: 80,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },

        {
          id: '0|Russia#RUS#',
          code: 'RUS',
          label: 'Russia',
          order: 133,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Non-OECD Economies#NMEC#|Russia#RUS#',
          code: 'RUS',
          label: 'Russia',
          order: 356,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Non-OECD Economies#NMEC#',
          level: 1,
          path: ['Non-OECD Economies#NMEC#'],
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Topic',
      label: 'Topic',
      values: [
        {
          id: '0|Environment#ENV#',
          code: 'ENV',
          label: 'Environment',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm15.32 0c-.86.08-1.7.2-2.5.38c-4.55 1.02-10.23 4.41-10.23 10.16c0 2.07.74 4.03 2.09 5.57c.26-4.6 2.14-8.92 5.33-12.26c1.58-1.65 3.41-2.97 5.31-3.85zm-9.26 23.29c0 .39.32.71.71.71c.39 0 .71-.32.71-.71l0-3.56c-.49-.19-.96-.42-1.42-.68l0 4.24zm15.35-22.66c-.09-.3-.36-.51-.68-.51c-3.25 0-6.88 1.76-9.7 4.71c-3.15 3.28-4.91 7.6-4.97 12.16c0 0 0 0 0 .01c0 0 0 0 0 0l0 .37c.11.07.21.15.32.22c3.28 2.16 7.73 1.79 10.6-1.08c2.49-2.49 1.97-5.91 1.8-7.84c-.26-2.93-.48-5.46 2.33-7.24c.27-.17.39-.5.3-.8z',
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Environment#ENV#|Air and Climate#ENV_AC#',
          code: 'ENV_AC',
          label: 'Air and Climate',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: true,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '0|Health#HEA#',
          code: 'HEA',
          label: 'Health',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm21.25 5.5h-4.25v-2c0-1.1-.9-2-2-2h-6c-1.1 0-2 .9-2 2v2h-4.25c-1.52 0-2.75 1.23-2.75 2.75v11.5c0 1.52 1.23 2.75 2.75 2.75h18.5c1.52 0 2.75-1.23 2.75-2.75v-11.5c0-1.52-1.23-2.75-2.75-2.75zm-12.25-2h6v2h-6zm9 11.25c0 .96-.78 1.75-1.75 1.75h-2.25v2.25c0 .97-.78 1.75-1.75 1.75h-.5c-.96 0-1.75-.78-1.75-1.75v-2.25h-2.25c-.96 0-1.75-.78-1.75-1.75v-.5c0-.96.78-1.75 1.75-1.75h2.25v-2.25c0-.97.78-1.75 1.75-1.75h.5c.96 0 1.75.78 1.75 1.75v2.25h2.25c.96 0 1.75.78 1.75 1.75z',
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Environment#ENV#|Waste#ENV_WAS#',
          code: 'ENV_WAS',
          label: 'Waste',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '1|Environment#ENV#|Water#ENV_WAT#',
          code: 'ENV_WAT',
          label: 'Water',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '0|Energy#NRG#',
          code: 'NRG',
          label: 'Energy',
          order: 5,
          count: 1,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm18.93.35c-.11-.21-.33-.35-.57-.35h-9.42c-.29 0-.54.19-.62.46l-3.37 11.28c-.06.2-.02.4.1.57c.12.16.31.26.52.26h5.28l-2.13 10.66c-.06.31.11.62.41.73c.07.03.15.04.22.04c.23 0 .44-.12.56-.33l8.3-14.57c.11-.2.11-.45 0-.64c-.11-.2-.33-.32-.56-.32h-3.74l4.97-7.12c.14-.2.15-.45.04-.67z',
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 1,
      hasPath: true,
    },
  ];
  const result = [
    {
      id: 'Variable',
      label: 'Variable',
      values: [
        {
          id: '0|Total emission intensities#INTENSITY#',
          code: 'INTENSITY',
          label: 'Total emission intensities',
          order: 0,
          count: null,
          isDisabled: true,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Total emission intensities#INTENSITY#|Total emissions per unit of GDP, Kg per 1000\n\t\t\t\t\t\tUSD#TOT_GDP#',
          code: 'TOT_GDP',
          label:
            'Total emissions per unit of GDP, Kg per 1000\n\t\t\t\t\t\tUSD',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Total emission intensities#INTENSITY#',
          level: 1,
          path: ['Total emission intensities#INTENSITY#'],
        },
        {
          id: '0|Total emissions, Index 1990 = 100#INDEX_1990#',
          code: 'INDEX_1990',
          label: 'Total emissions, Index 1990 = 100',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Total man-made emissions#TOT#',
          code: 'TOT',
          label: 'Total man-made emissions',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Country',
      label: 'Country',
      values: [
        {
          id: '0|Non-OECD Economies#NMEC#',
          code: 'NMEC',
          label: 'Non-OECD Economies',
          order: 0,
          count: null,
          isDisabled: true,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Australia#AUS#',
          code: 'AUS',
          label: 'Australia',
          order: 10,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Austria#AUT#',
          code: 'AUT',
          label: 'Austria',
          order: 20,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Costa Rica#CRI#',
          code: 'CRI',
          label: 'Costa Rica',
          order: 70,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Czech Republic#CZE#',
          code: 'CZE',
          label: 'Czech Republic',
          order: 80,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },

        {
          id: '0|Russia#RUS#',
          code: 'RUS',
          label: 'Russia',
          order: 133,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Non-OECD Economies#NMEC#|Russia#RUS#',
          code: 'RUS',
          label: 'Russia',
          order: 356,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Non-OECD Economies#NMEC#',
          level: 1,
          path: ['Non-OECD Economies#NMEC#'],
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Topic',
      label: 'Topic',
      values: [
        {
          id: '1|Environment#ENV#|Air and Climate#ENV_AC#',
          code: 'ENV_AC',
          label: 'Air and Climate',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: true,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '0|Environment#ENV#',
          code: 'ENV',
          label: 'Environment',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm15.32 0c-.86.08-1.7.2-2.5.38c-4.55 1.02-10.23 4.41-10.23 10.16c0 2.07.74 4.03 2.09 5.57c.26-4.6 2.14-8.92 5.33-12.26c1.58-1.65 3.41-2.97 5.31-3.85zm-9.26 23.29c0 .39.32.71.71.71c.39 0 .71-.32.71-.71l0-3.56c-.49-.19-.96-.42-1.42-.68l0 4.24zm15.35-22.66c-.09-.3-.36-.51-.68-.51c-3.25 0-6.88 1.76-9.7 4.71c-3.15 3.28-4.91 7.6-4.97 12.16c0 0 0 0 0 .01c0 0 0 0 0 0l0 .37c.11.07.21.15.32.22c3.28 2.16 7.73 1.79 10.6-1.08c2.49-2.49 1.97-5.91 1.8-7.84c-.26-2.93-.48-5.46 2.33-7.24c.27-.17.39-.5.3-.8z',
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Health#HEA#',
          code: 'HEA',
          label: 'Health',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm21.25 5.5h-4.25v-2c0-1.1-.9-2-2-2h-6c-1.1 0-2 .9-2 2v2h-4.25c-1.52 0-2.75 1.23-2.75 2.75v11.5c0 1.52 1.23 2.75 2.75 2.75h18.5c1.52 0 2.75-1.23 2.75-2.75v-11.5c0-1.52-1.23-2.75-2.75-2.75zm-12.25-2h6v2h-6zm9 11.25c0 .96-.78 1.75-1.75 1.75h-2.25v2.25c0 .97-.78 1.75-1.75 1.75h-.5c-.96 0-1.75-.78-1.75-1.75v-2.25h-2.25c-.96 0-1.75-.78-1.75-1.75v-.5c0-.96.78-1.75 1.75-1.75h2.25v-2.25c0-.97.78-1.75 1.75-1.75h.5c.96 0 1.75.78 1.75 1.75v2.25h2.25c.96 0 1.75.78 1.75 1.75z',
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '1|Environment#ENV#|Waste#ENV_WAS#',
          code: 'ENV_WAS',
          label: 'Waste',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '1|Environment#ENV#|Water#ENV_WAT#',
          code: 'ENV_WAT',
          label: 'Water',
          order: 0,
          count: 1,
          isDisabled: false,
          isSelected: false,
          parentId: '0|Environment#ENV#',
          level: 1,
          path: ['Environment#ENV#'],
        },
        {
          id: '0|Energy#NRG#',
          code: 'NRG',
          label: 'Energy',
          order: 5,
          count: 1,
          isDisabled: false,
          isSelected: false,
          svgPath:
            'm18.93.35c-.11-.21-.33-.35-.57-.35h-9.42c-.29 0-.54.19-.62.46l-3.37 11.28c-.06.2-.02.4.1.57c.12.16.31.26.52.26h5.28l-2.13 10.66c-.06.31.11.62.41.73c.07.03.15.04.22.04c.23 0 .44-.12.56-.33l8.3-14.57c.11-.2.11-.45 0-.64c-.11-.2-.33-.32-.56-.32h-3.74l4.97-7.12c.14-.2.15-.45.04-.67z',
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 1,
      hasPath: true,
    },
  ];
  const irrelevantFacets = [
    {
      id: 'Variable',
      label: 'Variable',
      values: [
        {
          id: '0|Total emissions, Index 1990 = 100#INDEX_1990#',
          code: 'INDEX_1990',
          label: 'Total emissions, Index 1990 = 100',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
        {
          id: '0|Total man-made emissions#TOT#',
          code: 'TOT',
          label: 'Total man-made emissions',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 0,
      hasPath: true,
    },
    {
      id: 'Pollutant',
      label: 'Pollutant',
      values: [
        {
          id: '0|Nitrogen Oxides#NOX#',
          code: 'NOX',
          label: 'Nitrogen Oxides',
          order: 0,
          count: 2,
          isDisabled: false,
          isSelected: false,
          parentId: null,
          level: 0,
          path: null,
        },
      ],
      count: 1,
      hasPath: true,
    },
  ];

  it('should not return facet with whose all values have count equals to search results count', () => {
    expect(rejectIrrelevantFacets({ count, locale })(facets)).toEqual(result);
  });

  it('should return empty facets array', () => {
    expect(rejectIrrelevantFacets({ count, locale })(irrelevantFacets)).toEqual(
      [],
    );
  });
});
